version: '3.9'

services:
  proxy-server:
    container_name: proxy-server
    build:
      context: ../..
      dockerfile: build/package/proxy/Dockerfile
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ../../configs:/configs
    command: /proxy-server
    